### ISSUE TITLE
Bug on syarat kelulusan list

### ISSUE THREAD

**Issue by davidatz285** [pascalalfadian/SIAModels#25]
Syarat kelulusan list mengandung "belum lulus skripsi 1 AIF184001" pada mahasiswa yang sedang skripsi 2 dan sudah lulus skripsi 1.

**Comment by pascalalfadian** [comment]
@davidatz285 bisa minta NPM nya? Akan saya cek datanya di SIAKAD.

**Comment by davidatz285** [comment]
NPM mahasiswa yang mengalami bug ini :
2017730015
2017730007

**Comment by pascalalfadian** [comment]
Hi @davidatz285 

Kalau di tempat saya (versi SIAModels nya memang berbeda, saya pakai v5.1.1; tapi diharapkan hasilnya sama), laporan untuk 2017730015 seperti ini:

```
Syarat kelulusan:
  Anda baru lulus 130 SKS, masih kurang 14 SKS lagi untuk mencapai 144.
  Anda belum lulus MK wajib AIF184000
  Anda belum mengambil MK AIF184001 & AIF184002 atau AIF184004
  Belum ada skor TOEFL.
```

Dikatakan belum mengambil AIF184001 *&* AIF184002. Maksudnya itu kedua mata kuliah tersebut harus sudah lulus. Statusnya saat ini kamu kan belum lulus skripsi 2, jadi kalau laporannya seperti di atas, artinya valid. Kalau di aplikasi kamu pesannya seperti apa ya?

**Comment by davidatz285** [comment]
Di aplikasi saya pesannya sama persis seperti yg bapak tulis di atas. Kalau pesan dari responden saya seperti ini :

`Jumlah SKS lulus benar, namun ada informasi tambahan bahwa belum mengambil AIF184001, AIF184002, dan AIF184004, padahal AIF184001 adalah Skripsi 1 dan sudah lulus, sedangkan AIF184002 adalah Skripsi 2 yang sedang diambil, dan otomatis tidak akan mengambil AIF184004 yaitu Tugas Akhir.`

Mungkin yang membuat dia bingung dan informasinya belum benar karena dia merasa dia sudah lulus skripsi 1 namun di aplikasi tertulis belum mengambil skripsi 1.

**Comment by pascalalfadian** [comment]
Responden maksudnya 2017730007 ya?

**Comment by davidatz285** [comment]
Iya betul Pak, yang bilang begitu di form survey saya adalah 2017730007.

**Comment by pascalalfadian** [comment]
Oke sip.. Kelihatannya salah memahami saja ya. Kalau begitu ini saya tutup dulu ya.
