### ISSUE TITLE
Bug on menghitung IPK

### ISSUE THREAD

**Issue by davidatz285** [pascalalfadian/SIAModels#26]
Pada kasus mahasiswa npm 2017730035, IPK yang dihitung dengan method calculateIPK() menghasilkan angka 2.48, sedangkan di Portal Akademik Mahasiswa IPK nya 2.57.

**Comment by pascalalfadian** [comment]
Ternyata saya tidak punya aksesnya untuk mahasiswa ini, karena ybs dosen walinya bukan saya. Jadi untuk sementara diclose dulu issuenya.
